services:
  temporal-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: temporal-api
    ports:
      - 8001:8001
    networks:
      - nauto
  temporal-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - nauto

networks:
  nauto:
    external: true
    name: nauto